function [dof] = read_dof(fname)
% [dof] = READ_DOF(fname)
%
%  Extracts the DOF list as a vector
%   from a .dof file generated by geomcal or mpr (both UMDS)
%

fid=fopen(fname);
while (~feof(fid)),
  str=fscanf(fid,'%s',1);
  if (strcmp(str,'DOF:')),
    dof=get_matrix(fid);
  end
end
fclose(fid);
return;


%-----------------------------------------

function g = get_matrix(fid)

num=fscanf(fid,'%d',1);
if (num<6)
 disp('Error in reading Linear_Transform matrix');
end
 g = fscanf(fid,'%f',inf);
 gl = length(g);
 g = reshape(g,gl/num,num).'; 
 gsz = size(g);
  % extract the last column
 if (gsz(2)>1)
   g = g(:,gsz(2));
 end
return;
